### ISSUE TITLE
convert-to / convert-from

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio_tools#10]
I seems to me that `convert-to` and `convert-from` are swapped: I am always confused in which one I should use!
I suggest to rename them such that `convert-to -t gamess` converts from TREXIO to GAMESS, and `convert-from -t gamess` converts from GAMESS to TREXIO.

**Comment by q-posev** [comment]
It is already like that ;-)

**Comment by scemama** [comment]
My bad.... I was a bit tired :-)
