### ISSUE TITLE
ORCA CI test failure

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio_tools#23]
@v1j4y @scemama 

I added the ORCA->TREXIO converter test for water molecule to CI. It fails [here](https://github.com/TREX-CoE/trexio_tools/actions/runs/6298620252/job/17097797132):

```
  File "/home/runner/.local/lib/python3.10/site-packages/trexio_tools/converters/orca_to_trexio.py", line 165, in gto_norm
    val = ((alpha + alpha)/np.pi)**(3/4)*((4*alpha)**((ax + ay + az)/2))/((scipy.special.factorial2(2*ax - 1) * \
ZeroDivisionError: float division by zero
```

**Comment by v1j4y** [comment]
Forgot to update the file fixed in #24 .

I don't get this error on my computer !

Looking into this.

**Comment by v1j4y** [comment]
This is fixed in [b890e5d](https://github.com/TREX-CoE/trexio_tools/pull/25/commits/b890e5d6f2c9aef6137d57fa47627ae971936b32)

@q-posev  Note that you added these extra lines to check other stuff

```python
grep "Norm of the error" < mos-res | grep -Eo "([0-9]+\.[0-9]*|\.?[0-9]+)([eE][+-][0-9]+)?" > error-res
python -c 'with open("error-res") as f: error = f.readline().strip(); assert float(error) < 1.0'
# benchmark the MOs by computing numerically integrals on a grid and comparing with the ref values from the file
trexio check-mos -n 50 trexio_pyscf_w.h5 > mos-res
```

These were causing failure of the CI. I removed these lines to check just for the ORCA CI.

Please check these lines independently !

**Comment by v1j4y** [comment]
Done !

**Comment by q-posev** [comment]
I suppose this is related to the versions of scipy that you have on your computer versus the CI runner. Thanks for fixing it!

**Comment by v1j4y** [comment]
Yeah, problems with the behavior of ```scipy.special.factorial2(-1)```

FYI, i removed these lines that you added, please check !

```python
grep "Norm of the error" < mos-res | grep -Eo "([0-9]+\.[0-9]*|\.?[0-9]+)([eE][+-][0-9]+)?" > error-res
python -c 'with open("error-res") as f: error = f.readline().strip(); assert float(error) < 1.0'
# benchmark the MOs by computing numerically integrals on a grid and comparing with the ref values from the file
trexio check-mos -n 50 trexio_pyscf_w.h5 > mos-res
```

**Comment by q-posev** [comment]
Yeah, I saw that, thanks! I did not expect the PySCF to fail, having a look now.

**Comment by q-posev** [comment]
@v1j4y @scemama

FYI, I added `check-mos` tests to CI for ORCA- and PySCF-based TREXIO files preceded by conversion from spherical to cartesian basis. Both are green, namely the norm of error is < 1.0. 

If you feel like it, I can make a new PyPI release of `trexio-tools`.

**Comment by v1j4y** [comment]
Awesome ! Thanks Evgeny :smile:
