### ISSUE TITLE
Converting GAMESS output with multistate calculation

### ISSUE THREAD

**Issue by neelravi** [TREX-CoE/trexio_tools#39]
When a Gamess output with multiple states is provided to `trexio convert-from` command, it fails with the following error:

```bash
trexio.Error: Inconsistent number of determinants
Exception ignored in: <function File.__del__ at 0x7bc5523298b0>
Traceback (most recent call last):
  File ".local/lib/python3.9/site-packages/trexio.py", line 209, in __del__
    _close(self.pytrexio_s)
  File ".local/lib/python3.9/site-packages/trexio.py", line 264, in _close
    raise Error(rc)
trexio.Error: Inconsistent number of determinants
```

The file is attached to reproduce this message. 
[test_gamess.txt](https://github.com/user-attachments/files/17486800/test_gamess.txt)

The possible solution is 

- [x] to create multiple trexio files for each state
- [x] copy the common data groups to every trexio file
- [x] update the state_id of each trexio file
- [x] update / copy the determinants and/or CSF information corresponding to each state

I am working on a pull request that achieves this. Let me know if this approach is optimal.

**Comment by q-posev** [comment]
Fixed in #53
