### ISSUE TITLE
Troubleshooting Determinant Import Issues in TREXIO with PySCF

### ISSUE THREAD

**Issue by NastaMauger** [TREX-CoE/trexio_tools#43]
Hello,

I am trying to import my casci wavefunction into qp2. To do so I am using trexio-tools.
After importing my one- and two-electron integrals and my TREXIO data from PySCF using:

```
qp_import_trexio.py casci.hdf5
qp set_file casci.hdf5.ezfio/
qp set mo_basis mo_label Canonical
qp_run import_trexio_integrals casci.hdf5.ezfio
qp_run print_energy casci.hdf5.ezfio
```

I can verify that it returns the same energy components as PySCF.
However, I would also like to import my determinants. To do so, I ran:
```
qp_run import_trexio_determinants casci.hdf5.ezfio/
```

However, I am experiencing a few issues:

1. The files created in `casci.hdf5.ezfio/determinants`, named `psi_det_qp_edit.gz` and `psi_det.gz`, don’t seem to contain meaningful data, although the corresponding coefficients files appear to be correct.
2. While no error occurs when running the `import_trexio_determinants` command, the `print_energy` command now fails with this error:

```
Providing the one-electron integrals
* N_int                                                          1
 * mo_label          Canonical
* Number of determinants                                         5
* Dimension of the psi arrays                                    5
 Read psi_det
 Read psi_coef           5           1
.. >>>>> [ IO READ: mo_class ] <<<<< ..
  cpu  time :  4.399999999998849E-005 s
  wall time :  7.152557373046875E-006 s  ( x    6.15164586666506      )
 MO map initialized:                   1540
 ac_operator: iorb < 1
    -1822208          10
-1
Program exited with code 255.
Wall time: 0:00:01
```

My guess is that I might not be registering my determinants list correctly. However, if this were the case, how could the `import_trexio_determinants` command run without issues?

Here is how I handled this in my PySCF script:

```
# Determinants in TREXIO
from trexio_tools.group_tools import determinant as trexio_det
int64_num = int((mo_num-1)/64) + 1 

det_list = []
#occsa is my spin up list whereas occsb is my spin down
for occsa, occsb, _, _ in data_all_sorted:
    det_tmp = []
    det_tmp += trexio_det.to_determinant_list(occsa, int64_num)
    det_tmp += trexio_det.to_determinant_list(occsb, int64_num)
    det_list.append(det_tmp)
    print(det_tmp)

offset_file = 0 
trexio_file.set_state(1)
trexio.write_state_num(trexio_file, 1)
trexio.write_determinant_list(trexio_file, offset_file, num_determinants, det_list)

ci_coeff_list = []
for occsa, occsb, ci_coeff, _ in data_all_sorted:
    ci_coeff_list.append(ci_coeff)

if len(ci_coeff_list) == num_determinants:
    dset = np.array(ci_coeff_list)  
    trexio.write_determinant_coefficient(trexio_file, offset_file, num_determinants, dset)
```

I’ve attached my [casci.hdf5](https://github.com/user-attachments/files/17672954/casci.hdf5.txt) file, generated by Pyscf for reference.

If anyone has insights into why this error is occurring or suggestions on how to resolve it, I would really appreciate your help. Thank you in advance!

Best

**Comment by q-posev** [comment]
Hello @NastaMauger ,
When using @scemama's resultsFile package to convert Gaussian/GAMESS CI determinants into TREXIO, we shift the orbitals by 1 (see [here](https://github.com/TREX-CoE/trexio_tools/blob/master/src/trexio_tools/converters/convert_from.py#L411)). Are the orbital indices in `occsa` 0-based or 1-based?
Or perhaps there is a bug in `import_trexio_determinants`. This is @scemama's call.

**Comment by NastaMauger** [comment]
Hello @q-posev 

I am a bit confused regarding the 0-based or 1-based question. 
This is what it looks like with Pyscf:
```
Full list of occupied up orbitals (with CI coefficients):
   det-alpha (occsa),         det-beta (occsb),
   [0 1]          [0 1]         -0.99779049148461
   [0 2]          [0 2]         0.033402646674729995
   [0 2]          [1 2]         -0.03321881541135069
   [1 2]          [0 2]         -0.03321881541135069
   [1 2]          [1 2]         0.033036629721523374
```
Best

**Comment by q-posev** [comment]
So the  PySCF orbital list is 0-based, meaning that the lowest orbital has index 0. I have a strong suspicion that the `to_determinant_list` function that you use expects the orbital list to be 1-based (namely the lowest orbital index starting from 1). Mainly because we compute `modulo = int((orb-1)/64)`. 0-based vs 1-based is similar to Python versus Fortran difference for indexing arrays. To be confirmed by @scemama.

So you can use the same trick as we do for GAMESS/Gaussian:
```python
orb_list_up  = [ orb+1 for orb in occsa ]
det_tmp += trexio_det.to_determinant_list(orb_list_up, int64_num)
```
and same for beta part.
Hope it helps!

**Comment by NastaMauger** [comment]
I have modified my code this way
```
det_list = []
for occsa, occsb, _, _ in data_all_sorted:
  occsa_upshifted = [orb + 1 for orb in occsa]  
  occsb_upshifted = [orb + 1 for orb in occsb]
  det_tmp     = []
  det_tmp    += trexio_det.to_determinant_list(occsa_upshifted, int64_num)
  det_tmp    += trexio_det.to_determinant_list(occsb_upshifted, int64_num)                                                                  
  det_list.append(det_tmp)
```
And the export works fine now with qp2.
` qp_run print_ci_vectors casci.hdf5.ezfio/` correctly shows my ci vectors however `qp-edit asci.hdf5.ezfio/` shows only one ci vector althought n_det is 5 in my case

Best

**Comment by NastaMauger** [comment]
Oh, I just realized you posted the same code solution as me, @q-posev. Sorry for the trouble and thank you so much! :)

**Comment by q-posev** [comment]
Good news! The rest is up to the QP2 gurus 😊

**Comment by scemama** [comment]
> And the export works fine now with qp2. `qp_run print_ci_vectors casci.hdf5.ezfio/` correctly shows my CI vectors; however, `qp_edit casci.hdf5.ezfio/` shows only one CI vector, even though `n_det` is 5 in my case. I’m not sure if this is normal or if it could be an issue for further calculations in QP2

OK. There is a little thing missing in qp `import_trexio_determinants` to make qp_edit work. I will fix it. As long as qp_run print_ci_vectors is correct, everything is fine.

**Comment by scemama** [comment]
@NastaMauger Can you upload your trexio file so I can search for the qp_edit problem please?

**Comment by NastaMauger** [comment]
Hello,

Here is the [casci.hdf5.ezfio.zip](https://github.com/user-attachments/files/17688653/casci.hdf5.ezfio.zip) file. As you might notice, psi_det_qp_edit.gz and psi_det.gz are different. I believe the export code is missing the ezfio.set_qp_edit_determinant function.

Best

**Comment by q-posev** [comment]
@NastaMauger small correction to your script: in TREXIO the ground state has id=0, so you should use `trexio_file.set_state(0)` to write the CI wave function for the ground state. Reference to the TREXIO doc:
![image](https://github.com/user-attachments/assets/637c3afd-d990-4df9-9d57-e29e1515b8eb)

**Comment by NastaMauger** [comment]
I have modified my script in #45.
Thank you for letting me know!
