### ISSUE TITLE
Clarify that orbital indices should be 0-based when creating a determinant list

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio_tools#45]
Improving docs and code

**Comment by NastaMauger** [comment]
Hello,

I think it might also be beneficial for users to have a direct example showing how to extract and register the determinants from a PySCF script.

For instance, I not only needed to confirm the 1-based indexing for the determinant list, but also to ensure that my TREXIO file contained the correct number of states (which, to be honest, was not obvious in my case since I am working with the ground state, and this section in the TREXIO documentation pertains to excited states).

The example determinant file you already have does not mention this. Additionally, converting to a bit-field format may not be obvious to some users. I believe you could directly use my PySCF script related to this part, which is attached.

```
# Determinans in Trexio
from trexio_tools.group_tools import determinant as trexio_det #To convert in bitfiled format
int64_num = int((mo_num-1)/64) + 1 


det_list = []
for occsa, occsb, _, _ in data_all_sorted: #occsa represent the alpha orbitals list whereas occsb is the beta one
  occsa_upshifted = [orb + 1 for orb in occsa]  #need +1 because pyscf orbital list is 0 based
  occsb_upshifted = [orb + 1 for orb in occsb]
  det_tmp     = []
  det_tmp    += trexio_det.to_determinant_list(occsa_upshifted, int64_num)
  det_tmp    += trexio_det.to_determinant_list(occsb_upshifted, int64_num)
  det_list.append(det_tmp)

offset_file = 0 
trexio_file.set_state(1)  #Needed otherwise qp2 export failed
trexio.write_state_num(trexio_file,1)  #Needed otherwise qp2 export failed
n_chunks = 1 
for _ in range(n_chunks):
  trexio.write_determinant_list(trexio_file, offset_file, num_determinants, det_list)
  offset_file += n_chunks


ci_coeff_list = []
for occsa, occsb, ci_coeff, _ in data_all_sorted:
    ci_coeff_list.append(ci_coeff)

if len(ci_coeff_list) == num_determinants:
    dset = np.array(ci_coeff_list)  
    trexio.write_determinant_coefficient(trexio_file, offset_file, num_determinants, dset)
```
Best

**Comment by q-posev** [comment]
Hello @NastaMauger ,

Thanks for your feedback!

> For instance, I not only needed to confirm the 1-based indexing for the determinant list, but also to ensure that my TREXIO file contained the correct number of states (which, to be honest, was not obvious in my case since I am working with the ground state, and this section in the TREXIO documentation pertains to excited states).

This is more of an issue of how TREXIO is imported in QP2 and is not related to `trexio-tools`. It is up to QP2 to raise a clear error if, as in your case, the state id/num is not provided. But I agree that this part of our documentation is not very intuitive (for historical reasons: determinants I/O came first, the treatment for excited states arrived later).

> The example determinant file you already have does not mention this and might not provide enough detail on how to do this from PySCF. Additionally, converting to a bit-field format may not be obvious depending on the user's level of knowledge. I believe you could directly use my PySCF script (which is highly inspired from your ResultsFIle work) related to this part, which is attached.

Thanks for sharing your script! We are currently at the crossroads because the PySCF integration is ongoing in two parallel slopes: 1) here in `trexio-tools` thanks to the work of @kousuke-nakano (converting PySCF CHK file into TREXIO) and 2) in the [pyscf-forge](https://github.com/pyscf/pyscf-forge) repository (via their dedicated function, so no CHK file needed, see PRs [1](https://github.com/pyscf/pyscf-forge/pull/60) and [2](https://github.com/pyscf/pyscf-forge/pull/68)). To me, it makes more sense to integrate your work directly in `pyscf-forge` so that one day it ends up in the upstream `pyscf` (leading to the deprecation of our pyscf->trexio converter).

But in the meantime, we can also integrate you determinant conversion in `trexio-tools`

@NastaMauger @scemama @kousuke-nakano what do you think about this? We can move this discussion elsewhere (e.g. in a dedicated issue). This one is more of a reminder for me to add the necessary checks to `to_determinant_list` :-)

**Comment by kousuke-nakano** [comment]
> Thanks for sharing your script! We are currently at the crossroads because the PySCF integration is ongoing in two parallel slopes: 1) here in trexio-tools thanks to the work of @kousuke-nakano (converting PySCF CHK file into TREXIO) and 2) in the [pyscf-forge](https://github.com/pyscf/pyscf-forge) repository (via their dedicated function, so no CHK file needed, see PRs https://github.com/pyscf/pyscf-forge/pull/60 and https://github.com/pyscf/pyscf-forge/pull/68). To me, it makes more sense to integrate your work directly in pyscf-forge so that one day it ends up in the upstream pyscf (leading to the deprecation of our pyscf->trexio converter).

Dear @q-posev, Yes, I agree with you. Once the issue we are discussing is solved, we should integrate our work directly into `pyscf-forge`.

**Comment by scemama** [comment]
Thanks @NastaMauger for your feedback!
I also agree that the contributions to pyscf should be done in the pyscf-forge, and that in the long term our converter should be deprecated.
However, the piece of code provided by @NastaMauger is a good example on how to write determinants, and we should add it as an example to the documentation, just like we have examples for reading integrals.

There is no way to make a robust 0/1-based indexing check. The only thing we can do is checking that the `0 <= mo index < mo.num`. All the determinants with electrons moved up one orbital are valid (as long as there is no overflow), and there is no assumption in TREXIO that the lowest orbital should be occupied.
