### ISSUE TITLE
NameError: name 'run_molden' is not defined

### ISSUE THREAD

**Issue by vvp-nsk** [TREX-CoE/trexio_tools#9]
Hi!

A conversion from a molden file into the TREXIO format is broken:

`trexio  convert-from -t molden -i h2o.molden h2o.trexio`

`Traceback (most recent call last):
  File "/home/victor/miniconda3/bin/trexio", line 8, in <module>
    sys.exit(main())
  File "/home/victor/miniconda3/lib/python3.7/site-packages/trexio_tools/trexio_run.py", line 93, in main
    run(args["TREXIO_FILE"], args["--input"], args["--type"], back_end=back_end)
  File "/home/victor/miniconda3/lib/python3.7/site-packages/converters/convert_from.py", line 435, in run
    run_molden(trexio_filename, filename, back_end)
NameError: name 'run_molden' is not defined
`

Indeed, the `run_molden` function is not defined within the `convert_from.py` source file while it is defined within the `convert_to.py` file. 

Could you please have a look at the issue? 

With best regards, 
[h2o.molden.zip](https://github.com/TREX-CoE/trexio_tools/files/8991119/h2o.molden.zip)

Victor Vysotskiy

**Comment by scemama** [comment]
Hi!
Yes, TREXIO -> molden is implemented but not the opposite.

**Comment by q-posev** [comment]
Hi @vvp-nsk ,

Thanks for bringing this up! Indeed, the molden -> TREXIO does not exist. It was mentioned [elsewhere](https://chemrxiv.org/engage/chemrxiv/article-details/60c75569702a9b991e18c6ca) that the `molden` format was loosely defined, making it difficult to be fully compatible with it.

**Comment by vvp-nsk** [comment]
Hi!

I see your concerns. Indeed, almost each QCh package uses own unique interpretation of the MOLDEN format. Therefore, it might be hard to maintain and support molden -> TREXIO converter. However, it is worth to add support of the `.fch(k)` and/or `wfn `file formats because many post-HF ab initio packages can dump all relevant information in such formats too. 

BTW, the issue can be closed. 

With best regards, 
Victor Vysotskiy

**Comment by q-posev** [comment]
You are right, implementing converters from `.wfn` or `.mwfn` can be useful. At the moment, I wonder whether interfacing with `IOData` Python [package](https://iodata.readthedocs.io/en/latest/) would be a better idea, based on the documentation it seems that they can parse most of the commonly used output formats (including the aforementioned ones). But I have not used this package myself, so any feedback is appreciated.

Thanks again, I will close this issue.

**Comment by vvp-nsk** [comment]
Hi again!

The IOData library should work fine for conversion among different formats. Alternatively, the [Molecular Orbital KIT (MOKIT)](https://gitlab.com/jxzou/mokit) transfers perfectly data between QCh packages seamlessly through .fchk.  In particular, we successfully transfer converged CAS orbitals from OpenMOLCAS to ORCA. 

With best regards, 
Victor Vysotskiy

**Comment by q-posev** [comment]
Thank you for the feedback @vvp-nsk ! We will have a look at the MOKIT too.

Kind regards,
Evgeny

**Comment by scemama** [comment]
It seems that IOData requires Cython, which introduces an extra dependency:
```
$ pip install iodata
Collecting iodata
  Downloading iodata-0.1.3.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cqbu_2m4/iodata_3aa275e17ddf4c5c971793954cd87a68/setup.py", line 3, in <module>
          import Cython.Build
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
 If we make trexio-tools depend on IOData, we will get intro trouble

**Comment by q-posev** [comment]
Yes, you are right. I had in mind a different approach where we integrate TREXIO into `IOData` and not the other way around. This gives us immediate benefit that whenever a new I/O format is added to the `IOData`, the corresponding converter to TREXIO is already in place. This is similar to what we initially wanted to achieve by integrating with `cclib`, but `IOData` seems more suitable for the I/O purposes + it supports more file formats at the moment.

**Comment by vvp-nsk** [comment]
Hi again!

Thanks for adding support of the MOLDEN format. To fix an incompatibility problem with a loosely defined MOLDEN's format, one can use the following tricks:

-  [Molden2AIM/Multiwfn/MOKIT](https://github.com/pyscf/pyscf/issues/758#issuecomment-731948152)
-  [The molden2molden tool](https://sourceforge.net/p/janpa/wiki/molden2molden/)

With best regards, 
Victor Vysotskiy
